import type { Product, Portfolio } from "@/types";

export const STATIC_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Hikvision DS-2CD2143G2-I 4MP AcuSense Fixed Dome",
    slug: "hikvision-ds-2cd2143g2-i",
    category: "IP_CAMERAS",
    brand: "Hikvision",
    model: "DS-2CD2143G2-I",
    description: "4MP AcuSense fixed dome network camera with deep learning AI, perfect for indoor and outdoor installation.",
    features: ["4MP resolution", "AcuSense AI detection", "IR up to 40m", "IP67 weatherproof", "IK10 vandal-resistant"],
    specifications: { "Resolution": "4MP (2688×1520)", "IR Range": "40m", "Lens": "2.8mm / 4mm / 6mm", "Weatherproof": "IP67", "Compression": "H.265+" },
    price: null,
    priceOnRequest: true,
    imageUrl: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=400&h=300&fit=crop",
    images: [],
    isActive: true,
    isFeatured: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "prod-2",
    name: "Dahua IPC-HDW2849H-S-IL 8MP Smart Dual Light Fixed-focal Eyeball",
    slug: "dahua-ipc-hdw2849h",
    category: "IP_CAMERAS",
    brand: "Dahua",
    model: "IPC-HDW2849H-S-IL",
    description: "8MP 4K Smart Dual Light fixed-focal eyeball network camera with AI detection and full-color night vision.",
    features: ["8MP 4K resolution", "Smart dual light", "Full color night vision", "AI human & vehicle detection", "H.265+ compression"],
    specifications: { "Resolution": "8MP (3840×2160)", "Night Vision": "Full Color + IR 30m", "Lens": "2.8mm", "Protection": "IP67, IK10" },
    price: null,
    priceOnRequest: true,
    imageUrl: "https://images.unsplash.com/photo-1586771107445-d3ca888129ff?w=400&h=300&fit=crop",
    images: [],
    isActive: true,
    isFeatured: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "prod-3",
    name: "Hikvision DS-2DE4425IWG-E PTZ Network Camera",
    slug: "hikvision-ds-2de4425iwg",
    category: "PTZ_CAMERAS",
    brand: "Hikvision",
    model: "DS-2DE4425IWG-E",
    description: "4MP 25× optical zoom PTZ camera with deep learning AI and long-range IR illumination for wide-area surveillance.",
    features: ["4MP resolution", "25× optical zoom", "IR range 100m", "Deep learning detection", "Auto-tracking"],
    specifications: { "Resolution": "4MP", "Optical Zoom": "25×", "IR Range": "100m", "Pan Range": "360° endless", "Tilt Range": "-15° to 90°" },
    price: null,
    priceOnRequest: true,
    imageUrl: "https://images.unsplash.com/photo-1563461660947-507ef49e9c47?w=400&h=300&fit=crop",
    images: [],
    isActive: true,
    isFeatured: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "prod-4",
    name: "Hikvision DS-7608NI-K2/8P 8-Channel NVR",
    slug: "hikvision-ds-7608ni-k2-8p",
    category: "NVR_DVR",
    brand: "Hikvision",
    model: "DS-7608NI-K2/8P",
    description: "8-channel PoE NVR supporting up to 8MP cameras with 2 SATA HDD bays and H.265+ compression.",
    features: ["8-channel PoE", "Supports up to 8MP", "2× SATA HDD", "H.265+ compression", "HDMI & VGA output", "Remote access"],
    specifications: { "Channels": "8", "Max Resolution": "8MP", "HDD Bays": "2 (up to 10TB each)", "PoE Power": "8×PoE, total 100W", "Bandwidth": "80Mbps" },
    price: null,
    priceOnRequest: true,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
    images: [],
    isActive: true,
    isFeatured: false,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "prod-5",
    name: "Dahua DHI-NVR4108HS-8P-4KS2/L 8CH PoE NVR",
    slug: "dahua-dhi-nvr4108hs-8p",
    category: "NVR_DVR",
    brand: "Dahua",
    model: "DHI-NVR4108HS-8P-4KS2/L",
    description: "Compact 8-channel 4K NVR with built-in 8-port PoE switch, supporting AI features and H.265+ video compression.",
    features: ["8-channel 4K", "Built-in 8-port PoE", "H.265+ compression", "Smart detection", "P2P remote access"],
    specifications: { "Channels": "8", "Max Resolution": "4K (8MP)", "PoE Ports": "8", "HDD Bays": "1 (up to 8TB)" },
    price: null,
    priceOnRequest: true,
    imageUrl: null,
    images: [],
    isActive: true,
    isFeatured: false,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "prod-6",
    name: "Hikvision DS-K1T341CMF Face Recognition Terminal",
    slug: "hikvision-ds-k1t341cmf",
    category: "ACCESS_CONTROL",
    brand: "Hikvision",
    model: "DS-K1T341CMF",
    description: "AI-powered face recognition access control terminal with card, fingerprint, and PIN authentication.",
    features: ["Face recognition", "Fingerprint scanner", "Card & PIN access", "Temperature detection", "Time attendance"],
    specifications: { "Face Capacity": "6,000", "Card Capacity": "100,000", "Verification Time": "< 0.2s", "Display": "4.3\" touch screen" },
    price: null,
    priceOnRequest: true,
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&h=300&fit=crop",
    images: [],
    isActive: true,
    isFeatured: false,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "prod-7",
    name: "CP Plus CP-E24B Bullet Camera 2MP Full HD",
    slug: "cp-plus-cp-e24b",
    category: "ANALOG_HD",
    brand: "CP Plus",
    model: "CP-E24B",
    description: "2MP Full HD bullet camera with 40m IR range, suitable for outdoor perimeter security.",
    features: ["2MP Full HD", "40m IR range", "IP66 weatherproof", "Wide dynamic range", "Day/night switching"],
    specifications: { "Resolution": "2MP (1920×1080)", "IR Range": "40m", "Lens": "3.6mm", "Weatherproof": "IP66" },
    price: 2499,
    priceOnRequest: false,
    imageUrl: null,
    images: [],
    isActive: true,
    isFeatured: false,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "prod-8",
    name: "Dahua VTO2211G-P IP Video Door Phone",
    slug: "dahua-vto2211g-p",
    category: "INTERCOM",
    brand: "Dahua",
    model: "VTO2211G-P",
    description: "PoE-powered HD video door phone with two-way audio, night vision, and mobile app access.",
    features: ["HD video", "Two-way audio", "Night vision", "Mobile app unlock", "Tamper detection", "IP65 weatherproof"],
    specifications: { "Resolution": "2MP", "Night Vision": "Yes", "PoE": "IEEE 802.3af", "Connectivity": "Wi-Fi + Ethernet" },
    price: null,
    priceOnRequest: true,
    imageUrl: null,
    images: [],
    isActive: true,
    isFeatured: false,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
];

export const STATIC_PORTFOLIOS: Portfolio[] = [
  {
    id: "port-1",
    title: "Kumar Textiles Factory — 48 Camera Installation",
    slug: "kumar-textiles-factory",
    clientName: "Kumar Textiles Pvt Ltd",
    clientIndustry: "Manufacturing",
    location: "Thane, Maharashtra",
    summary: "Complete surveillance overhaul for a 120,000 sq ft textile manufacturing facility with AI-powered analytics.",
    challenge: "The factory had outdated analog cameras with poor coverage, blind spots in the production floor, and no remote monitoring capability.",
    solution: "Designed and installed 48 IP cameras including PTZ cameras for wide-area coverage, integrated with AI video analytics for perimeter intrusion detection and unauthorized access alerts.",
    outcome: "100% facility coverage achieved. Remote monitoring from management's mobile devices. Security incidents reduced by 78%. ROI achieved within 18 months.",
    camerasInstalled: 48,
    projectDuration: "2 weeks",
    coverageArea: "120,000 sq ft",
    beforeImageUrl: null,
    afterImageUrl: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=500&fit=crop",
    galleryImages: [],
    tags: ["Industrial", "IP Cameras", "PTZ", "AI Analytics", "Remote Monitoring"],
    isPublished: true,
    isFeatured: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "port-2",
    title: "Horizon IT Park — Multi-Floor Office Complex",
    slug: "horizon-it-park",
    clientName: "Horizon IT Park",
    clientIndustry: "Commercial",
    location: "Pune, Maharashtra",
    summary: "8-floor IT park surveillance system with access control and visitor management integration.",
    challenge: "Multiple tenants required individual access control while the building management needed centralized surveillance.",
    solution: "Installed 64 IP cameras across all floors with floor-wise access control. Integrated video analytics for people counting and occupancy monitoring.",
    outcome: "Tenant satisfaction improved significantly. Operational costs reduced by 30% through automated monitoring.",
    camerasInstalled: 64,
    projectDuration: "3 weeks",
    coverageArea: "250,000 sq ft",
    beforeImageUrl: null,
    afterImageUrl: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&h=500&fit=crop",
    galleryImages: [],
    tags: ["Commercial", "Office", "Access Control", "Video Analytics"],
    isPublished: true,
    isFeatured: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "port-3",
    title: "Sunrise International School — Child Safety System",
    slug: "sunrise-international-school",
    clientName: "Sunrise International School",
    clientIndustry: "Education",
    location: "Thane, Maharashtra",
    summary: "Comprehensive child safety surveillance with facial recognition for authorized visitor management.",
    challenge: "School needed to ensure child safety with unknown visitor alerts and complete campus coverage.",
    solution: "32 cameras with facial recognition for staff and authorized visitors. Real-time alerts for unknown faces. Safe zone monitoring around school gates.",
    outcome: "Zero security incidents post-installation. Parent confidence increased significantly. Compliant with school safety regulations.",
    camerasInstalled: 32,
    projectDuration: "10 days",
    coverageArea: null,
    beforeImageUrl: null,
    afterImageUrl: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&h=500&fit=crop",
    galleryImages: [],
    tags: ["Education", "Facial Recognition", "Child Safety", "IP Cameras"],
    isPublished: true,
    isFeatured: false,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
];
